#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xrandr --output Virtual-1 --mode 1920x1080 &
betterlockscreen -w &
picom & 

# Привязка рабочих столов к монитору(ам)
bspc monitor -d p i z d e c
# Рамки и отступы
bspc config border_width         1
bspc config window_gap          10

# Цвет рамки
bspc config normal_border_color "#CCFFFF"
bspc config active_border_color "#336699"
bspc config focused_border_color "663399"

# Цвет пространства при выборе положения нового окна
bspc config presel_feedback_color "#595B82"

# Фокус окна наведение курсора
bspc config focus_follows_pointer true
bspc config pointer_modifier	super

# Коэффициент разделение. Сколько процентов останется от родительского окна при открытии нового
bspc config split_ratio          0.52

# Отступы и рамки, когда открыто одно окно
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config paddingless_monocle	 true

# Схема открытия нового окна
#bspc config automatic_scheme	spiral

# Правила приложений
bspc rule -a Gimp desktop='3'
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh
